config/routes.rb
Rails.application.routes.draw do


	# sessions gets singular resource as there can only ever be one session
	resource :session
  	resources :rooms, except: [:new, :create] do
  		resources :orders, only: [:new, :create]
  	end
  	resources :users do
  		# this is for passing through user id when creating room
  		resources :rooms, only: [:new, :create]
  		resources :orders, only: [:show]
  	end
  	root "rooms#index"

end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :user
	belongs_to :room

	def save_with_payment!
		# Set your secret key: remember to change this to your live secret key in production
			# See your keys here https://dashboard.stripe.com/account
			Stripe.api_key = Rails.application.secrets.stripe_secret_key

			# Get the credit card details submitted by the form
			token = self.stripe_token

			# Create the charge on Stripe's servers - this will charge the user's card
			begin
			  charge = Stripe::Charge.create(
			    :amount => self.room.price_in_pence, # amount in pence, again
			    :currency => "gbp",
			    :card => token,
			    :description => self.user.email
			  )
			self.save!
			rescue Stripe::CardError => e
			  # The card has been declined

			end
		end

end

app/models/room.rb
class Room < ActiveRecord::Base

	validates :title, presence: true
	validates :address, presence: true
	validates :price_in_pence, presence: true
	validates :no_of_rooms, presence: true
	# sayin that when it is created, the default is false (this is only on create)
	#validates :is_featured, presence: true #, inclusion: { in: [false]}, on: :create
	# this is on update as well
	#validates :is_featured, presence: true
	validates :description, length: {minimum: 10}


	has_attached_file :image, :styles => { :large => "1000x664>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	belongs_to :user
	has_many :orders

end

app/models/user.rb
class User < ActiveRecord::Base

	#http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html
	has_secure_password

	validates :email, presence: true, uniqueness: true
	validates :username, presence: true, uniqueness: true

	has_many :rooms
	has_many :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	if session[:user_id].present?
  		User.find(session[:user_id])
  	end
  end

  def logged_in?
  	session[:user_id].present?
  end

  def require_user
  	unless logged_in?
  		flash[:error] = "You need to be logged in"
  		redirect_to new_session_path
  	end
  end

  # to prevent non-owners of rooms from editing (via url)
  def current_user_owns_room

  	# Then find the room that is trying to be edited
  	room = Room.find(params[:id])
  	# And only allow if current user made that room
  	unless logged_in? and current_user == room.user
  		# Otherwise flash error and redirect to show page
  		flash[:error] = "Only the owner can edit"
  		# (room) indicates the requirement for an id form the url
  		redirect_to room_path(room)  		
  	end
  end

  #these are now available everywhere as they are being defined in the Apllication controller
  # helper_method :require_user
  helper_method :current_user
  helper_method :logged_in?


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :require_user, only: [:new, :create, :show]
	before_action :find_user, only: [:new, :create, :show]
	before_action :find_room, only: [:new, :create]

  def new
  	@order = @room.orders.new
  	@order.user_id = @user.id
  end

  def create
  	@order = @room.orders.new(order_params)
  	@order.user_id = @user.id
  	if @order.save_with_payment!
  		
  		flash[:success] = "Thanks for booking!"
  		redirect_to user_order_path(@user, @order)
  	else
  		flash[:error] = "That didnt work"
  		render :new
  	end
  end

  def show
  	@order = Order.find(params[:id])
  end


  private

  def order_params
  	params.require(:order).permit(:stripe_token, :user_id, :room_id)
  end

  def find_user
  	#current_user is a helper method from application controller
  	@user = current_user
  end

  def find_room
  	@room = Room.find(params[:room_id])
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

	# call the require_method helper method before new and create (rather than individually further down)
	before_action :require_user, only: [:new, :create]
	before_action :current_user_owns_room, only: [:edit, :update]
	before_action :find_room, only: [:show, :edit, :update]

  def index
  	@rooms = Room.all
  end

  def show
  	# Was first: @room = Room.find(params[:id])
  	# Then to (with helper in appliaction controller): find_room
  	# Then moved to top
  end
  
  def new
  	# require_user
  	# used to be this, but need to pass through user id @room = Room.new

  	# Find the user from the URL
  	@user = User.find(params[:user_id])
  	@room = @user.rooms.new
  end

  def create
  	# require_user
  	@user = User.find(params[:user_id])
  	@room = @user.rooms.new(room_params)

  	@room.price_in_pence = params[:room][:price_in_pence] 

  	if @room.save
  		flash[:success] = "All done"
  		redirect_to root_path
  	else
  		flash[:error] = "Nope"
  		render :new
  	end
  end

  def edit
  	# moved to top: current_user_owns_room
  	# moved to top: @room = Room.find(params[:id])
  end

  def update
  	# moved to top: current_user_owns_room
  	# same as new apart from (same for most apps)
  	# .new beceomes .find
  	# .save becomes .update
  	# room_params moves to update
  	# moved to top: @room = Room.find(params[:id])
  	if @room.update(room_params)
  		flash[:success] = "All done"
  		redirect_to root_path
  	else
  		flash[:error] = "Nope"
  		render :new
  	end
  end

  def find_room
  	@room = Room.find(params[:id])
  end

  private
  def room_params
  	params.require(:room).permit(:title, :address, :description, :no_of_rooms, :price_in_pence, :user_id, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  # This logs us in
  def create
  	# We get the email and the password from the params object (up here)
  	@email = params[:session][:email]
  	@password = params[:session][:password]

  	# And query the users table for a user with email equal to @email
  	@user = User.find_by(email: @email)

  	# Only if there is a User with email equal to @email
  	# And that users password is correct, will be logged in
  	if @user.present? and @user.authenticate(@password)
  		# Personalised flash message. Anything inside #{ } is read as ruby
  		flash[:success] = "Welcome back #{@user.name}"
  		session[:user_id] = @user.id
  		redirect_to root_path
  	else
  		flash[:error] = "Try again"
  		render :new  		
  	end
  end

  # This logs us out
  def destroy
  	reset_session
  	flash[:success] = "You have logged out"
  	redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end


  def create
  	@user = User.new(user_params)
  		if @user.save
  			flash[:success] = "That worked"
  			redirect_to root_path
  		else
  			flash[:error] = "Didnt work"
  			render :new
  		end
  	end


  	private
  	def user_params
  		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<nav>
		
		<div>
			<%= link_to "Onboard", root_path%>
		</div>

		

		<% if logged_in? %>

			<!-- Show user name -->
			<span><%= current_user.username %></span>
			<!-- links for users -->
			<!-- Update to new room path to carry through user id -->
			<%= link_to "Add a room", new_user_room_path(current_user.id) %>
			<%= link_to "Log out", session_path, method: :delete %>

		<% else %>

			<!-- links for non user -->
			<%= link_to "Sign up", new_user_path %>
			<%= link_to "Log in", new_session_path %>

		<% end %>
	</nav>
</header>


<% flash.each do |key,value| %>
	<div class="<%= key %>">
		<p><%= value %></p>
	</div>
<% end %>

<%= yield %>

</body>
</html>

app/views/orders/new.html.erb
<%= simple_form_for [@room, @order] do |f| %>
	  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <%= f.button :submit, "Buy" %>

 <% end %>

 <script type="text/javascript" src="https://js.stripe.com/v2/"></script>

 <script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_hudKokQbJHXqNzUzqJt5reYh');
  // ...
  jQuery(function($) {
  $('#new_order').submit(function(event) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});

function stripeResponseHandler(status, response) {
  var $form = $('#new_order');

  if (response.error) {
    // Show the errors on the form
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // response contains id and card, which contains additional card details
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    $form.append($('<input type="hidden" name="order[stripe_token]" />').val(token));
    // and submit
    $form.get(0).submit();
  }
};

</script>

app/views/orders/show.html.erb
<p><%= "Hi #{@user.name}! Thanks for booking #{@order.room.title}" %></p>

<%= @order.room.title %>
<%= @order.room.address %>
<%= @order.room.description %>

<%= @order.inspect %>
<%= @user.inspect %>

app/views/rooms/_form.html.erb
<!-- Adding '@user' here puts @user.id in the user_id col of hte rooms table -->

<%= simple_form_for [@user, @room] do |f| %>

	<%= f.input :title %>
	<%= f.input :address %>
	<%= f.input :description %>
	<%= f.input :image %>
	<%= f.input :no_of_rooms %>
	<%= f.input :price_in_pence, label: "Price" %>

	<%= f.button :submit %>


<% end %>

app/views/rooms/edit.html.erb
<%= render "form" %>

app/views/rooms/index.html.erb
<% @rooms.each do |room| %>

	<!-- (room) in backets is because it is looking for a number in the url, - room.id -->
	<%= link_to room_path(room) do %>
		<h3><%= room.title %></h3>
		<p><%= room.address %></p>
		<p><%= room.price_in_pence %></p>
		<p><%= image_tag room.image.url(:thumb) %></p>
	<% end %>

<% end %>

app/views/rooms/new.html.erb
<%= render "form" %>

app/views/rooms/show.html.erb
<p><%= image_tag @room.image.url(:large) %></p>
<h1><%= @room.title %></h1>
<p><%= @room.address %></p>
<p><%= @room.description %></p>
<p>£<%= @room.price_in_pence / 100 %> per day</p>
<p><%= @room.no_of_rooms %> rooms</p>
<p>To enquire about this room, email <%= mail_to @room.user.email, "#{@room.user.name}" %></p>


<!--  -->

<% if logged_in? and not current_user == @room.user %>
	<%= link_to "Book this room", new_room_order_path(@room) %>
<% end %>

<% if logged_in? and current_user == @room.user %>
	<!-- (@room) takes the id - look at routes -->
	<%= link_to "Edit", edit_room_path(@room) %>
<% end %>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>

	<%= f.input :name %>
	<%= f.input :username %>
	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>

	<%= f.button :submit, "Sign up" %>

<% end %>